apiVersion: v2
name: nats-operator
description: A Helm chart for deploying the NATS Operator on Kubernetes
type: application
version: 0.1.0
appVersion: "v0.1.0"
home: https://github.com/crewlet/nats-operator
sources:
  - https://github.com/crewlet/nats-operator
maintainers:
  - name: crewlet
    url: https://github.com/crewlet
